AWSTemplateFormatVersion: '2010-09-09'
Description: "Frontend Stack: S3, CloudFront & CI/CD (Node.js build)"

Parameters:
  EnvironmentName:
    Type: String
    Default: prod
  FrontendBucketName:
    Type: String
    Default: "my-app-frontend-assets"
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
    Default: "main"
  GitHubToken:
    Type: String
    NoEcho: true
  BackendApiUrl:
    Type: String
    Description: "Optional: API URL from Backend Stack (for env vars)"
    Default: ""

Resources:
  # --- Hosting Resources ---
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvironmentName}-${FrontendBucketName}"
      AccessControl: Private # Best practice: use OAI/OAC, but keeping simple based on original
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

  FrontendCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          ForwardedValues:
            QueryString: false
            Cookies: { Forward: none }
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # --- CI/CD (Frontend Only) ---
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: { Status: Enabled }

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{Effect: Allow, Principal: {Service: codebuild.amazonaws.com}, Action: sts:AssumeRole}]
      ManagedPolicyArns: [ "arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess" ]

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{Effect: Allow, Principal: {Service: codepipeline.amazonaws.com}, Action: sts:AssumeRole}]
      ManagedPolicyArns: [ "arn:aws:iam::aws:policy/AWSCodePipelineFullAccess" ]

  FrontendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${EnvironmentName}-frontend-build"
      ServiceRole: !Ref CodeBuildRole
      Artifacts: { Type: CODEPIPELINE }
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: VITE_API_URL
            Value: !Ref BackendApiUrl
      Source: { Type: CODEPIPELINE }
      BuildSpec: |
        version: 0.2
        phases:
          install:
            runtime-versions:
              nodejs: 14
            commands:
              - echo Installing dependencies...
              - npm install
          build:
            commands:
              - echo Building React app...
              - npm run build
        artifacts:
          files:
            - '**/*'
          base-directory: build

  FrontendPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId: { Category: Source, Owner: ThirdParty, Provider: GitHub, Version: '1' }
              OutputArtifacts: [{ Name: SourceOutput }]
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
        - Name: Build
          Actions:
            - Name: BuildReact
              ActionTypeId: { Category: Build, Owner: AWS, Provider: CodeBuild, Version: '1' }
              InputArtifacts: [{ Name: SourceOutput }]
              OutputArtifacts: [{ Name: BuildOutput }]
              Configuration: { ProjectName: !Ref FrontendBuildProject }
        - Name: Deploy
          Actions:
            - Name: DeployToS3
              ActionTypeId: { Category: Deploy, Owner: AWS, Provider: S3, Version: '1' }
              InputArtifacts: [{ Name: BuildOutput }]
              Configuration:
                BucketName: !Ref FrontendBucket
                Extract: 'true'

Outputs:
  CloudFrontURL:
    Value: !GetAtt FrontendCloudFront.DomainName